---
title: "Imagery Priming"
format: html
editor: visual
---

```{r setup}
library(tidyverse) #manipulating data
library(here) #managing directories

all_data <- list.files(here("data","raw-data", "BR"), pattern = "\\.csv$", full.names = TRUE) %>%
  map_dfr(function(file) {
    read_csv(file) %>%
      filter(!is.na(label)) %>% #only real trials, no staircase trials
      select(label, visualCue, probe_loc, probe_response, subj_response, vivid_response, participant)%>% #selecting columns of interest
      mutate( #creates new columns
        source_file = basename(file),
        trial_type = case_when(
          str_detect(label, "Incongruent") ~ "incongruent", #Trials are congruent when the cue/imagined stimulus is the one the probe disappeared
          str_detect(label, "Congruent") ~ "congruent",
          TRUE ~ "control"),
        probe_color = case_when(
          str_detect(label, "RedProbe") ~ "red",
          str_detect(label, "GreenProbe")~ "green"
          ),
        correct = if_else(probe_loc == probe_response, 1, 0)
      )
  })

#Order subjective responses
all_data<-all_data %>% 
  mutate(subj_response = factor(subj_response, levels = c("allgreen","mostlygreen","evensplit","mostlyred","allred")))

all_data<- all_data%>%
#the column mostlys_equal_all count the subject reports that are mostly red/green as all red/green  
  mutate(`mostlys_equal_all` = case_when(
    visualCue == "red"   & subj_response == "evensplit" ~ "RM",
    visualCue == "red"   & subj_response == "allred" |
      visualCue == "red" & subj_response == "mostlyred" ~ "RR",
    visualCue == "red"   & subj_response == "allgreen"  |
      visualCue== "red" &subj_response == "mostlygreen" ~ "RG",
    visualCue == "green" & subj_response == "allgreen"|
      visualCue == "green" & subj_response== "mostlygreen"~ "GG",
    visualCue == "green" & subj_response == "evensplit" ~ "GM",
    visualCue == "green" & subj_response == "allred"|
      visualCue == "green" & subj_response == "mostlyred"~ "GR",
    TRUE ~ NA_character_  # fallback
  )) %>% 
## The column mostly_equal_mixed count the subjective reports that are mostly red/green as mixed
    mutate(`mostlys_equal_mixed` = case_when(
    visualCue == "red" & subj_response == "allred" ~ "RR",
    visualCue == "red" & subj_response == "allgreen" ~ "RG",
    visualCue == "red" & subj_response == "mostlyred" |
      visualCue == "red" & subj_response == "mostlygreen"|
      visualCue == "red" & subj_response == "evensplit"~ "RM",
    visualCue == "green" & subj_response == "mostlyred" |
      visualCue == "green" & subj_response == "mostlygreen"|
      visualCue == "green" & subj_response == "evensplit"~ "GM",
    visualCue == "green" & subj_response == "allred" ~ "GR",
    visualCue == "green" & subj_response == "allgreen" ~ "GG"
  ))

#Get VVIQ and VVIQ2 Scores and combine with other data
vviq_data<- read_csv(here("data","raw-data","vviq.csv"))


vviq_data<- vviq_data %>% rename("participant" = "QID78")%>% 
  rename("VVIQ2"= "SC0") %>%
  rename("VVIQ"= "SC1")
  
#fix mislabeled participant id 
vviq_data <- vviq_data %>% 
  mutate(participant = recode(participant, "260404oj" = "260406oj"))

#remove hf (incorrect controls)
all_data<- all_data %>%
  filter(participant !='050526hf')

#select columns of interest
vviq_data<- vviq_data %>%
  select(participant,VVIQ2,VVIQ)

#combine binocular rivalry data with vviq data
all_data<- inner_join(all_data,vviq_data, by = "participant")

#ensure that vviq scores are numeric
all_data$VVIQ<-as.numeric(all_data$VVIQ)
all_data$VVIQ2<-as.numeric(all_data$VVIQ2)

write_csv(all_data,here("data","clean_data.csv"))
```

#### Subjective priming score

$$ \%primed =\frac{ n_{RR}+ n_{GG} + 0.5*n_{RM}+0.5*n_{GM}}{n_{RR} + n_{GG} + 0.5*n_{RM} +0.5*n_{GM}+n_{RG}+n_{GR}}$$

```{r}
#calculate the number each type of response-cue pairing for each subject 

subj_priming_resp<- all_data %>% 
  group_by(participant) %>%
  count(mostlys_equal_all) %>% 
  pivot_wider(names_from = mostlys_equal_all, values_from = n, values_fill = 0)

prime_scores_sub<- subj_priming_resp %>% 
  summarise(subj_prime = ((GG + RR + (0.5*GM) + (0.5*RM)))/((GG + RR + (0.5*GM) + (0.5*RM)+RG+GR)), .groups = "drop")

subj_priming_resp<- left_join(subj_priming_resp,prime_scores_sub, by= "participant")
  
```

```{r}
## creates 
survey_data <- all_data %>%
  group_by(participant) %>% 
  summarise(
    VVIQ = mean(VVIQ, na.rm = TRUE),
    VVIQ2 = mean(VVIQ2, na.rm = TRUE),
    avg_vividness = mean(vivid_response, na.rm = TRUE), .groups = "drop")

accuracy_data<- all_data %>% 
    group_by(participant, trial_type) %>%
  summarise(accuracy = mean(correct, na.rm = TRUE), .groups = "drop") %>%
  pivot_wider(names_from = trial_type, values_from = accuracy) %>%
  mutate(
    congruence_effect = congruent - incongruent)
#combining survey,accuracy,and subj priming score data
between_subj<- inner_join(survey_data,accuracy_data,by = "participant")
between_subj<- left_join(between_subj,subj_priming_resp, by = "participant")

write_csv(between_subj,here("data","between_subj.csv"))
```
