---
title: "01explore-and-check-assumptions"
format: html
---

```{r}
library(ggplot2) #creating plots
library(tidyverse) #data cleaning 
library(here) #managing directories, points to Rproj as working directory
library(DataExplorer) #probably won't use, auto generates exploratory analysis
library(gt) #for creating tables

all_data<- read_csv(here("data","clean_data.csv"),show_col_types = FALSE)
between_subj <- read_csv(here("data","between_subj.csv"), show_col_types = FALSE)
```



```{r}
ggplot(between_subj, aes(x= participant, y=VVIQ))+
  geom_col()
```


```{r}
ggplot(between_subj, aes(x= participant, y=VVIQ2))+
  geom_col()
```



```{r}
ggplot(between_subj, aes(x= avg_vividness))+
  geom_histogram(binwidth=1)

```


```{r}
ggplot(all_data, aes(x=vivid_response))+
  geom_histogram(binwidth=1)+
  facet_wrap(~participant)
```

```{r}
plot_data<- all_data%>%
  count(participant, subj_response) %>%
  mutate(prop= n/sum(n))
ggplot(plot_data, aes(x=subj_response, prop))+
  geom_col()+
  facet_wrap(~participant)
```

