---
title: "Imagery Priming"
format: html
editor: visual
---

```{r setup}
library(tidyverse) #manipulating data
library(here) #managing directories
library(ggplot2) #making graphs

all_data <- list.files(here("data", "BR"), pattern = "\\.csv$", full.names = TRUE) %>%
  map_dfr(function(file) {
    read_csv(file) %>%
      filter(!is.na(label)) %>% #only real trials, no staircase trials
      select(label, visualCue, probe_loc, probe_response, subj_response, vivid_response, participant)%>% 
      mutate(
        source_file = basename(file),
        trial_type = case_when(
          str_detect(label, "Incongruent") ~ "probe-cue-incongruent", #Trials are congruent when the cue/imagined stimulus is the one the probe disappeared
          str_detect(label, "Congruent") ~ "probe-cue-congruent",
          TRUE ~ "control"),
        probe_color = case_when(
          str_detect(label, "RedProbe") ~ "red",
          str_detect(label, "GreenProbe")~ "green"
          ),
        correct = if_else(probe_loc == probe_response, 1, 0)
      )
  })

#Order subject responses
all_data<-all_data %>% 
  mutate(subj_response = factor(subj_response, levels = c("allgreen","mostlygreen","evensplit","mostlyred","allred")))

all_data<- all_data%>%
#the column mostlys_equal_all count the subject reports that are mostly red/green as all red/green  
  mutate(`mostlys_equal_all` = case_when(
    visualCue == "red"   & subj_response == "evensplit" ~ "RM",
    visualCue == "red"   & subj_response == "allred" |
      visualCue == "red" & subj_response == "mostlyred" ~ "RR",
    visualCue == "red"   & subj_response == "allgreen"  |
      visualCue== "red" &subj_response == "mostlygreen" ~ "RG",
    visualCue == "green" & subj_response == "allgreen"|
      visualCue == "green" & subj_response== "mostlygreen"~ "GG",
    visualCue == "green" & subj_response == "evensplit" ~ "GM",
    visualCue == "green" & subj_response == "allred"|
      visualCue == "green" & subj_response == "mostlyred"~ "GR",
    TRUE ~ NA_character_  # fallback
  )) %>% 
## The column mostly_equal_mixed count the subjective reports that are mostly red/green as mixed
    mutate(`mostlys_equal_mixed` = case_when(
    visualCue == "red" & subj_response == "allred" ~ "RR",
    visualCue == "red" & subj_response == "allgreen" ~ "RG",
    visualCue == "red" & subj_response == "mostlyred" |
      visualCue == "red" & subj_response == "mostlygreen"|
      visualCue == "red" & subj_response == "evensplit"~ "RM",
    visualCue == "green" & subj_response == "mostlyred" |
      visualCue == "green" & subj_response == "mostlygreen"|
      visualCue == "green" & subj_response == "evensplit"~ "GM",
    visualCue == "green" & subj_response == "allred" ~ "GR",
    visualCue == "green" & subj_response == "allgreen" ~ "GG"
  ))

#Get VVIQ and VVIQ2 Scores and combine with other data
vviq_data<- read_csv(here("data","vviq.csv"))

#vviq_data<- vviq_data[,20:54] 

vviq_data<- vviq_data %>% rename("participant" = "QID78")%>% 
  rename("VVIQ2"= "SC0") %>%
  rename("VVIQ"= "SC1")
  

vviq_data<- vviq_data %>%
  select(participant,VVIQ2,VVIQ)

all_data<- inner_join(all_data,vviq_data, by = "participant")

all_data$VVIQ<-as.numeric(all_data$VVIQ)
all_data$VVIQ<-as.numeric(all_data$VVIQ2)
```

```{r}
g<-all_data %>%
  #group_by(participant) %>%
  ggplot(aes(x =subj_response))+
  geom_bar()+
  facet_wrap(~ participant)

```

```{r}
summary(all_data)
```

```{r}

subject_summary <- all_data %>%
  mutate(vivid_response = as.numeric(vivid_response)) %>%
  group_by(participant) %>%
  filter(subj_response == "allgreen"| subj_response =="allred") %>% 
  summarise(
    avg_vivid_response = mean(vivid_response, na.rm = TRUE),
    prop_correct_congruent = mean(correct[trial_type == "probe-cue-congruent"], na.rm = TRUE),
    prop_correct_incongruent = mean(correct[trial_type == "probe-cue-incongruent"], na.rm = TRUE),
    prop_correct_control_vividness = mean(correct[trial_type == "control"], na.rm = TRUE)
  )

subject_summary

complete_rival<- all_data %>% 
  filter(subj_response=="allred" | subj_response =="allgreen") %>% 
  filter(trial_type != "control")


```
